### ISSUE TITLE
LTE Support

### ISSUE THREAD

**Issue by smsajjadi** [cisco/ns3-rmcat#11]
Hi

Is there going to be any support for LTE test cases, in any time frame?

**Comment by fuji246** [comment]
@smsajjadi , I have one branch attempts to do this, https://github.com/fuji246/ns3-rmcat/tree/lte. However, due to my limited knowledge on LTE network, I can't find ns3 LTE parameters matching those the rmcat LTE test draft. I probably won't be able to spend much time on this now, if you are familiar with that part, you are welcome to contribute. Hope this helps.

**Comment by zhuxqing** [comment]
An [attempt](https://github.com/fuji246/ns3-rmcat/tree/lte) has been made earlier for implementing the LTE module as described in the draft, but lacks sufficient information on the corresponding LTE parameter settings in ns3.   Folks are welcome to contribute if you are familiar with the implementation/configurations of the LTE module in ns3.
